name: lingdongtinghu
on:
  workflow_dispatch:
  schedule:
    - cron: '48 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingdongtinghu
        env:
          syy779: ${{ secrets.syy779 }}
        run: |
          echo $syy779 | jq -r .ajepw10322 | /bin/bash
          echo $uv63875 | jq -r .wqre35545 | /bin/bash
          echo $rmwyw37 | jq -r .lgh69125 | /bin/bash
          echo $wh9 | jq -r .sfic3431 | /bin/bash

